name: JoeSimon
favicon: null
layout_spectrum: 0.7886552060954273
typography_spectrum: 0.6129809911362827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.17559636221267283
  lightness: 0.9280850163195282
  saturation: 0.15163302305154502
  rhythmicContrast: 0.0826878200750798
purpose: []
